In [1]:
from numpy import save
import mne
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

def datos(file):
    data = mne.io.read_raw_edf(f'{file}.edf')
    raw_data = data.get_data()
    events, events_id = mne.events_from_annotations(data)
    tmax = 30. - 1. / data.info['sfreq']  # tmax in included

    epochs_train = mne.Epochs(raw=data, events=events,
                              event_id=events_id, tmin=0., tmax=tmax, baseline=None, event_repeated='merge')
    patatuela = epochs_train.load_data()
    id_to_class_dict = {value:key for key, value in patatuela.event_id.items()}

    objective_stages = ['Sleep stage N1','Sleep stage N2','Sleep stage N3','Sleep stage R','Sleep stage W']
    epochs_to_df = [a for a in patatuela]
    epochs_to_df = []
    label_to_df = []
    for epoch, label in zip(patatuela, patatuela.events[:,-1]):
        # print(label)
        label = id_to_class_dict[label]
        if label in objective_stages:
            # print("True")
            epochs_to_df.append(epoch)
            label_to_df.append(label)
    dict_to_df = {"Epoch":epochs_to_df,"Label":label_to_df}
    df1=pd.DataFrame(dict_to_df)
    valores=df1.Epoch.values
    channels = data.ch_names
    diccionarios=[dict(zip(channels, sublist)) for sublist in valores]
    c3=[d['C3'] for d in diccionarios]
    c4=[d['C4'] for d in diccionarios]
    o1=[d['O1'] for d in diccionarios]
    o2=[d['O2'] for d in diccionarios]
    loc=[d['LOC'] for d in diccionarios]
    roc=[d['ROC'] for d in diccionarios]
    chin=[d['CHIN1'] for d in diccionarios]
    matriz=np.array([c3,c4,o1,o2,loc,roc,chin])

    name=file
    save(f'datos_{name}.npy', matriz)
    df1.Label.to_csv(f'Etiquetas_{name}.csv',index=None)

    return matriz, df1.Label

In [2]:
filess=[f'PSG{i}' for i in range(1,15)]

In [7]:
for fil in filess:
    print(datos(fil))

Extracting EDF parameters from C:\Users\parod\OneDrive\Escritorio\Máster IA UV\TFM\PSG1.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...


<ipython-input-1-22fafd115996>:8: RuntimeWarning: Omitted 3 annotation(s) that were outside data range.
  data = mne.io.read_raw_edf(f'{file}.edf')
<ipython-input-1-22fafd115996>:8: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  data = mne.io.read_raw_edf(f'{file}.edf')


Used Annotations descriptions: ['EEG arousal', 'Hypopnea', 'Impedance at 10 kOhm', 'Lights Off', 'Limb Movement', 'Montage:PR, Ref', 'Obstructive Apnea', 'Oximeter Event', 'Oxygen Desaturation', 'Pulse Rate Event', 'Recording Analyzer - Auto-Staging', 'Recording Analyzer - Data Trends', 'Recording Analyzer - ECG', 'Recording Analyzer - Sleep Events', 'Sleep stage N1', 'Sleep stage N2', 'Sleep stage N3', 'Sleep stage R', 'Sleep stage W', 'Snoring', 'Start Recording', 'Started Analyzer - Sleep Events', 'Video Recording ON']
Not setting metadata
Multiple event values for single event times found. Creating new event value to reflect simultaneous events.
Not setting metadata
3031 matching events found
No baseline correction applied
0 projection items activated
Loading data for 3031 events and 15360 original time points ...
1 bad epochs dropped
(array([[[-4.17761501e-04, -4.17761501e-04, -4.14795148e-04, ...,
         -9.47585260e-05, -1.02668803e-04, -9.67360952e-05],
        [-9.27809567e-

<ipython-input-1-22fafd115996>:8: RuntimeWarning: Omitted 6 annotation(s) that were outside data range.
  data = mne.io.read_raw_edf(f'{file}.edf')
<ipython-input-1-22fafd115996>:8: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  data = mne.io.read_raw_edf(f'{file}.edf')


Used Annotations descriptions: ['Central Apnea', 'Central Hypopnea', 'EEG arousal', 'ENTRO A COLOCAR PULSIOXIMETRO', 'ENTRO PARA ARREGLAR CHIN', 'Hypopnea', 'Impedance at 10 kOhm', 'Lights Off', 'Limb Movement', 'Mixed Apnea', 'Mixed Hypopnea', 'Montage:PR, Ref', 'Obstructive Apnea', 'Obstructive Hypopnea', 'Oximeter Event', 'Oxygen Desaturation', 'Pulse Rate Event', 'Recording Analyzer - Auto-Staging', 'Recording Analyzer - Data Trends', 'Recording Analyzer - ECG', 'Recording Analyzer - Sleep Events', 'Sleep stage ?', 'Sleep stage N1', 'Sleep stage N2', 'Sleep stage N3', 'Sleep stage R', 'Sleep stage W', 'Snoring', 'Start Recording', 'Started Analyzer - ECG', 'Started Analyzer - Sleep Events', 'Tachycardia', 'Video Recording ON']
Not setting metadata
Multiple event values for single event times found. Creating new event value to reflect simultaneous events.
Not setting metadata
1287 matching events found
No baseline correction applied
0 projection items activated
Loading data for 1287

<ipython-input-1-22fafd115996>:8: RuntimeWarning: Omitted 2 annotation(s) that were outside data range.
  data = mne.io.read_raw_edf(f'{file}.edf')
<ipython-input-1-22fafd115996>:8: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  data = mne.io.read_raw_edf(f'{file}.edf')


Used Annotations descriptions: ['Bradycardia', 'Central Apnea', 'EEG arousal', 'Hypopnea', 'Impedance at 10 kOhm', 'Lights Off', 'Lights On', 'Limb Movement', 'Mixed Apnea', 'Montage:PR, Ref', 'Obstructive Apnea', 'Obstructive Hypopnea', 'Oximeter Event', 'Oxygen Desaturation', 'Recording Analyzer - Auto-Staging', 'Recording Analyzer - Data Trends', 'Recording Analyzer - ECG', 'Recording Analyzer - Sleep Events', 'Sleep stage N1', 'Sleep stage N2', 'Sleep stage N3', 'Sleep stage R', 'Sleep stage W', 'Snoring', 'Start Recording', 'Started Analyzer - Sleep Events', 'Stopped Analyzer - Sleep Events', 'Video Recording ON']
Not setting metadata
Multiple event values for single event times found. Creating new event value to reflect simultaneous events.
Not setting metadata
1724 matching events found
No baseline correction applied
0 projection items activated
Loading data for 1724 events and 15360 original time points ...
3 bad epochs dropped
(array([[[-3.87109178e-04, -3.87768368e-04, -3.894

<ipython-input-1-22fafd115996>:8: RuntimeWarning: Omitted 39 annotation(s) that were outside data range.
  data = mne.io.read_raw_edf(f'{file}.edf')
<ipython-input-1-22fafd115996>:8: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  data = mne.io.read_raw_edf(f'{file}.edf')


Used Annotations descriptions: ['EEG arousal', 'Gain/Filter Change', 'Headbox Disconnecting', 'Hypopnea', 'Impedance at 10 kOhm', 'Lights Off', 'Limb Movement', 'Montage:PR, Ref', 'NO ENTRO POR EKG', 'Obstructive Hypopnea', 'Oxygen Desaturation', 'Pulse Rate Event', 'Recording Analyzer - Auto-Staging', 'Recording Analyzer - Data Trends', 'Recording Analyzer - ECG', 'Recording Analyzer - Sleep Events', 'Sleep stage N1', 'Sleep stage N2', 'Sleep stage N3', 'Sleep stage R', 'Sleep stage W', 'Snoring', 'Start Recording', 'Started Analyzer - Sleep Events', 'Video Recording ON', 'Video System Error']
Not setting metadata
Multiple event values for single event times found. Creating new event value to reflect simultaneous events.
Not setting metadata
1990 matching events found
No baseline correction applied
0 projection items activated
Loading data for 1990 events and 15360 original time points ...
1 bad epochs dropped
(array([[[-1.27718013e-04, -1.28706798e-04, -1.30025177e-04, ...,
         

<ipython-input-1-22fafd115996>:8: RuntimeWarning: Omitted 143 annotation(s) that were outside data range.
  data = mne.io.read_raw_edf(f'{file}.edf')
<ipython-input-1-22fafd115996>:8: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  data = mne.io.read_raw_edf(f'{file}.edf')


Used Annotations descriptions: ['Central Apnea', 'EEG arousal', 'Gain/Filter Change', 'Hypopnea', 'Impedance at 10 kOhm', 'Lights Off', 'Limb Movement', 'Montage:PSG CO2, Ref', 'ORINANDO', 'Obstructive Apnea', 'Obstructive Hypopnea', 'Oxygen Desaturation', 'Patient Event', 'Pulse Rate Threshold Event', 'Recording Analyzer - Auto-Staging', 'Recording Analyzer - Data Trends', 'Recording Analyzer - ECG', 'Recording Analyzer - Sleep Events', 'Sleep stage N1', 'Sleep stage N2', 'Sleep stage N3', 'Sleep stage R', 'Sleep stage W', 'Snoring', 'SpO2 Threshold Event', 'Start Recording', 'Started Analyzer - Sleep Events', 'Video Recording ON']
Not setting metadata
Multiple event values for single event times found. Creating new event value to reflect simultaneous events.
Not setting metadata
1525 matching events found
No baseline correction applied
0 projection items activated
Loading data for 1525 events and 15360 original time points ...
1 bad epochs dropped
(array([[[ 9.21382467e-04,  4.480842

<ipython-input-1-22fafd115996>:8: RuntimeWarning: Omitted 234 annotation(s) that were outside data range.
  data = mne.io.read_raw_edf(f'{file}.edf')
<ipython-input-1-22fafd115996>:8: RuntimeWarning: Limited 3 annotation(s) that were expanding outside the data range.
  data = mne.io.read_raw_edf(f'{file}.edf')


Used Annotations descriptions: ['Central Apnea', 'EEG arousal', 'Gain/Filter Change', 'Hypopnea', 'Impedance at 10 kOhm', 'Lights Off', 'Limb Movement', 'Mixed Apnea', 'Montage:PR, Ref', 'Obstructive Apnea', 'Obstructive Hypopnea', 'Oxygen Desaturation', 'Patient Event', 'Pulse Rate Threshold Event', 'Recording Analyzer - Auto-Staging', 'Recording Analyzer - Data Trends', 'Recording Analyzer - ECG', 'Recording Analyzer - Sleep Events', 'Sleep stage N1', 'Sleep stage N2', 'Sleep stage N3', 'Sleep stage R', 'Sleep stage W', 'Snoring', 'SpO2 Threshold Event', 'Start Recording', 'Started Analyzer - Sleep Events', 'Tachycardia', 'Video Recording ON']
Not setting metadata
Multiple event values for single event times found. Creating new event value to reflect simultaneous events.
Not setting metadata
2767 matching events found
No baseline correction applied
0 projection items activated
Loading data for 2767 events and 15360 original time points ...
6 bad epochs dropped
(array([[[ 1.13875029e-

<ipython-input-1-22fafd115996>:8: RuntimeWarning: Omitted 113 annotation(s) that were outside data range.
  data = mne.io.read_raw_edf(f'{file}.edf')
<ipython-input-1-22fafd115996>:8: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  data = mne.io.read_raw_edf(f'{file}.edf')


Used Annotations descriptions: ['Bradycardia', 'EEG arousal', 'Gain/Filter Change', 'Hypopnea', 'Impedance at 10 kOhm', 'Lights Off', 'Limb Movement', 'Montage:PR, Ref', 'Obstructive Apnea', 'Obstructive Hypopnea', 'Oxygen Desaturation', 'Patient Event', 'Recording Analyzer - Auto-Staging', 'Recording Analyzer - Data Trends', 'Recording Analyzer - ECG', 'Recording Analyzer - Sleep Events', 'Sleep stage N1', 'Sleep stage N2', 'Sleep stage N3', 'Sleep stage R', 'Sleep stage W', 'Snoring', 'Start Recording', 'Started Analyzer - Sleep Events', 'Video Recording ON']
Not setting metadata
Multiple event values for single event times found. Creating new event value to reflect simultaneous events.
Not setting metadata
2698 matching events found
No baseline correction applied
0 projection items activated
Loading data for 2698 events and 15360 original time points ...
7 bad epochs dropped
(array([[[ 9.37697414e-05,  8.35523003e-05,  5.61959258e-05, ...,
          1.23103685e-04,  1.08601511e-04, 

<ipython-input-1-22fafd115996>:8: RuntimeWarning: Omitted 4 annotation(s) that were outside data range.
  data = mne.io.read_raw_edf(f'{file}.edf')
<ipython-input-1-22fafd115996>:8: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  data = mne.io.read_raw_edf(f'{file}.edf')


Used Annotations descriptions: ['Bradycardia', 'CAMBIO A2', 'Central Apnea', 'Central Hypopnea', 'EEG arousal', 'ENTRO A REVISAR FLOW', 'Gain/Filter Change', 'Hypopnea', 'Impedance at 10 kOhm', 'Lights Off', 'Limb Movement', 'Mixed Apnea', 'Montage:PR, Ref', 'Obstructive Apnea', 'Obstructive Hypopnea', 'Oxygen Desaturation', 'Patient Event', 'REVISOMA2', 'Recording Analyzer - Auto-Staging', 'Recording Analyzer - Data Trends', 'Recording Analyzer - ECG', 'Recording Analyzer - Sleep Events', 'Sleep stage N1', 'Sleep stage N2', 'Sleep stage N3', 'Sleep stage R', 'Sleep stage W', 'Snoring', 'Start Recording', 'Started Analyzer - Sleep Events', 'TIENE FRIO LE PONGO UNA MANTA', 'Tachycardia']
Not setting metadata
Multiple event values for single event times found. Creating new event value to reflect simultaneous events.
Not setting metadata
1005 matching events found
No baseline correction applied
0 projection items activated
Loading data for 1005 events and 15360 original time points ...
1 

<ipython-input-1-22fafd115996>:8: RuntimeWarning: Omitted 99 annotation(s) that were outside data range.
  data = mne.io.read_raw_edf(f'{file}.edf')
<ipython-input-1-22fafd115996>:8: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  data = mne.io.read_raw_edf(f'{file}.edf')


Used Annotations descriptions: ['EEG arousal', 'Gain/Filter Change', 'Hypopnea', 'Impedance at 10 kOhm', 'Lights Off', 'Limb Movement', 'Montage:PSG CO2, Ref', 'Obstructive Apnea', 'Obstructive Hypopnea', 'Oxygen Desaturation', 'Patient Event', 'Pulse Rate Threshold Event', 'Recording Analyzer - Auto-Staging', 'Recording Analyzer - Data Trends', 'Recording Analyzer - ECG', 'Recording Analyzer - Sleep Events', 'Sleep stage N1', 'Sleep stage N2', 'Sleep stage N3', 'Sleep stage R', 'Sleep stage W', 'Snoring', 'SpO2 Threshold Event', 'Start Recording', 'Started Analyzer - Sleep Events', 'Tachycardia', 'Video Recording ON']
Not setting metadata
Multiple event values for single event times found. Creating new event value to reflect simultaneous events.
Not setting metadata
1429 matching events found
No baseline correction applied
0 projection items activated
Loading data for 1429 events and 15360 original time points ...
1 bad epochs dropped
(array([[[-1.68587778e-04, -4.13476768e-04, -5.861

<ipython-input-1-22fafd115996>:8: RuntimeWarning: Omitted 109 annotation(s) that were outside data range.
  data = mne.io.read_raw_edf(f'{file}.edf')


Used Annotations descriptions: ['Central Apnea', 'EEG arousal', 'Gain/Filter Change', 'Hypopnea', 'Impedance at 10 kOhm', 'Lights Off', 'Limb Movement', 'Montage:PSG CO2, Ref', 'Obstructive Apnea', 'Obstructive Hypopnea', 'Oxygen Desaturation', 'Pulse Rate Threshold Event', 'Recording Analyzer - Auto-Staging', 'Recording Analyzer - Data Trends', 'Recording Analyzer - ECG', 'Recording Analyzer - Sleep Events', 'Sleep stage N1', 'Sleep stage N2', 'Sleep stage N3', 'Sleep stage W', 'SpO2 Threshold Event', 'Start Recording', 'Started Analyzer - Sleep Events', 'Video Recording ON']
Not setting metadata
Multiple event values for single event times found. Creating new event value to reflect simultaneous events.
Not setting metadata
1295 matching events found
No baseline correction applied
0 projection items activated
Loading data for 1295 events and 15360 original time points ...
0 bad epochs dropped
(array([[[ 8.90400549e-04,  1.24669261e-03,  1.16594186e-03, ...,
         -1.35957885e-04, -

<ipython-input-1-22fafd115996>:8: RuntimeWarning: Omitted 92 annotation(s) that were outside data range.
  data = mne.io.read_raw_edf(f'{file}.edf')
<ipython-input-1-22fafd115996>:8: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  data = mne.io.read_raw_edf(f'{file}.edf')


Used Annotations descriptions: ['Bradycardia', 'Central Apnea', 'EEG arousal', 'Gain/Filter Change', 'Hypopnea', 'Impedance at 10 kOhm', 'Lights Off', 'Limb Movement', 'Montage:PR, Ref', 'Obstructive Apnea', 'Obstructive Hypopnea', 'Oxygen Desaturation', 'Patient Event', 'Pulse Rate Threshold Event', 'Recording Analyzer - Auto-Staging', 'Recording Analyzer - Data Trends', 'Recording Analyzer - ECG', 'Recording Analyzer - Sleep Events', 'Sleep stage N1', 'Sleep stage N2', 'Sleep stage N3', 'Sleep stage R', 'Sleep stage W', 'Snoring', 'SpO2 Threshold Event', 'Start Recording', 'Started Analyzer - Sleep Events', 'Tachycardia', 'Video Recording ON']
Not setting metadata
Multiple event values for single event times found. Creating new event value to reflect simultaneous events.
Not setting metadata
3903 matching events found
No baseline correction applied
0 projection items activated
Loading data for 3903 events and 15360 original time points ...
2 bad epochs dropped
(array([[[-1.99240101e-

<ipython-input-1-22fafd115996>:8: RuntimeWarning: Omitted 120 annotation(s) that were outside data range.
  data = mne.io.read_raw_edf(f'{file}.edf')
<ipython-input-1-22fafd115996>:8: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  data = mne.io.read_raw_edf(f'{file}.edf')


Used Annotations descriptions: ['EEG arousal', 'Gain/Filter Change', 'Hypopnea', 'Impedance at 10 kOhm', 'Lights Off', 'Limb Movement', 'Montage:PSG CO2, Ref', 'Obstructive Apnea', 'Obstructive Hypopnea', 'Oxygen Desaturation', 'Pulse Rate Threshold Event', 'Recording Analyzer - Auto-Staging', 'Recording Analyzer - Data Trends', 'Recording Analyzer - ECG', 'Recording Analyzer - Sleep Events', 'Sleep stage N1', 'Sleep stage N2', 'Sleep stage N3', 'Sleep stage R', 'Sleep stage W', 'Snoring', 'SpO2 Threshold Event', 'Start Recording', 'Started Analyzer - Sleep Events', 'Tachycardia', 'Video Recording ON']
Not setting metadata
Multiple event values for single event times found. Creating new event value to reflect simultaneous events.
Not setting metadata
1143 matching events found
No baseline correction applied
0 projection items activated
Loading data for 1143 events and 15360 original time points ...
1 bad epochs dropped
(array([[[ 5.92776379e-04,  1.15341726e-03,  1.36666514e-03, ...,
 

<ipython-input-1-22fafd115996>:8: RuntimeWarning: Omitted 2 annotation(s) that were outside data range.
  data = mne.io.read_raw_edf(f'{file}.edf')
<ipython-input-1-22fafd115996>:8: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  data = mne.io.read_raw_edf(f'{file}.edf')


Used Annotations descriptions: ['AHORA QUE ESTA MÃ\x81S TRANQUILO Y FINALIZANDO ', 'Bradycardia', 'CON LOS MOVIMIENTOS SE HABIA DOBLADO CANULA', 'CUANDO SE DESPIERTE REVISARE CHIN', 'CUANDO SE MUEVA REVISO BANDA ABD.', 'Central Apnea', 'EEG arousal', 'EKG CORRECTO', 'ENTRO A REVISAR FLOW', 'ESTA TODO DOBLADO A LA PART IZQ. POR ESO MALA SEÃ\x91AL EKG', 'Gain/Filter Change', 'Hypopnea', 'Impedance at 10 kOhm', 'Lights Off', 'Lights On', 'Limb Movement', 'Montage:PR, Ref', 'NO VOY A ENTRAR POR ekg', 'Obstructive Apnea', 'Obstructive Hypopnea', 'Oxygen Desaturation', 'REVISO MONTAJE', 'Recording Analyzer - Auto-Staging', 'Recording Analyzer - Data Trends', 'Recording Analyzer - ECG', 'Recording Analyzer - Sleep Events', 'SE MUEVE MUCHO ESTA TODO SUDADO', 'Sleep stage N1', 'Sleep stage N2', 'Sleep stage N3', 'Sleep stage R', 'Sleep stage W', 'Snoring', 'SpO2 Threshold Event', 'Start Recording', 'Started Analyzer - Sleep Events']
Not setting metadata
Multiple event values for single event ti

<ipython-input-1-22fafd115996>:8: RuntimeWarning: Omitted 104 annotation(s) that were outside data range.
  data = mne.io.read_raw_edf(f'{file}.edf')
<ipython-input-1-22fafd115996>:8: RuntimeWarning: Limited 2 annotation(s) that were expanding outside the data range.
  data = mne.io.read_raw_edf(f'{file}.edf')


Used Annotations descriptions: ['EEG arousal', 'Gain/Filter Change', 'Hypopnea', 'Impedance at 10 kOhm', 'Lights Off', 'Limb Movement', 'Montage:PSG CO2, Ref', 'Obstructive Apnea', 'Oxygen Desaturation', 'Pulse Rate Threshold Event', 'Recording Analyzer - Auto-Staging', 'Recording Analyzer - Data Trends', 'Recording Analyzer - ECG', 'Recording Analyzer - Sleep Events', 'Sleep stage N1', 'Sleep stage N2', 'Sleep stage N3', 'Sleep stage R', 'Sleep stage W', 'Snoring', 'SpO2 Threshold Event', 'Start Recording', 'Started Analyzer - Sleep Events', 'Video Recording ON']
Not setting metadata
Multiple event values for single event times found. Creating new event value to reflect simultaneous events.
Not setting metadata
2003 matching events found
No baseline correction applied
0 projection items activated
Loading data for 2003 events and 15360 original time points ...
4 bad epochs dropped
(array([[[-7.82787823e-05, -9.50881209e-05, -9.34401465e-05, ...,
         -5.88326848e-05, -3.90569924e-0

In [12]:
datos=[f'datos_PSG{i}.npy' for i in range(1,15)]

In [16]:
matriz_tocha=[np.load(d) for d in datos]

In [24]:
np.shape(matriz_tocha[0])

(7, 882, 15360)

In [25]:
matriz_tocha[0:10]

[array([[[-4.17761501e-04, -4.17761501e-04, -4.14795148e-04, ...,
          -9.47585260e-05, -1.02668803e-04, -9.67360952e-05],
         [-9.27809567e-05, -8.42114900e-05, -8.98146029e-05, ...,
          -1.79134813e-04, -1.85067521e-04, -1.90011444e-04],
         [-1.92977798e-04, -1.94296178e-04, -1.94625772e-04, ...,
          -3.47722591e-05, -3.08171206e-05, -2.65323873e-05],
         ...,
         [-4.92744335e-05, -4.66376745e-05, -5.22407874e-05, ...,
           8.73426413e-06,  8.07507439e-06,  1.00526436e-05],
         [ 1.10414282e-05,  6.42710002e-06,  5.76791028e-06, ...,
           6.83909361e-05,  6.67429618e-05,  6.77317464e-05],
         [ 6.97093156e-05,  7.10276951e-05,  6.93797208e-05, ...,
          -8.23987182e-07,  1.10414282e-05,  2.45548180e-05]],
 
        [[-3.59423209e-04, -3.52172122e-04, -3.56127260e-04, ...,
          -1.71554131e-04, -1.80123598e-04, -1.75509270e-04],
         [-1.78146029e-04, -1.73861295e-04, -1.75509270e-04, ...,
          -9.40993362

In [43]:
etiquetas=[f'Etiquetas_PSG{i}.csv' for i in range(1,15)]

In [53]:
et_todas=[pd.read_csv(d).iloc[:,0] for d in etiquetas]

In [54]:
et_todas

[0      Sleep stage W
 1      Sleep stage W
 2      Sleep stage W
 3      Sleep stage W
 4      Sleep stage W
            ...      
 877    Sleep stage W
 878    Sleep stage W
 879    Sleep stage W
 880    Sleep stage W
 881    Sleep stage W
 Name: Label, Length: 882, dtype: object,
 0       Sleep stage W
 1       Sleep stage W
 2       Sleep stage W
 3       Sleep stage W
 4       Sleep stage W
             ...      
 835    Sleep stage N3
 836    Sleep stage N3
 837    Sleep stage N3
 838    Sleep stage N3
 839    Sleep stage N3
 Name: Label, Length: 840, dtype: object,
 0       Sleep stage W
 1       Sleep stage W
 2       Sleep stage W
 3       Sleep stage W
 4       Sleep stage W
             ...      
 848    Sleep stage N2
 849    Sleep stage N2
 850    Sleep stage N2
 851    Sleep stage N2
 852    Sleep stage N2
 Name: Label, Length: 853, dtype: object,
 0      Sleep stage W
 1      Sleep stage W
 2      Sleep stage W
 3      Sleep stage W
 4      Sleep stage W
            ... 